config/routes.rb
Rails.application.routes.draw do
  namespace :founder do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  namespace :investor do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  resources :physical_locations
  namespace :user_profile, path: :profile do
    resources :personals, path: :personal
    resources :professionals, path: :professional, except: [:new, :create]
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # TODO: omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
    require "sidekiq/web"
    Sidekiq::Web.app_url = "/"
    mount Sidekiq::Web => "/sidekiq"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#index", as: :app_index

  scope "dashboard", controller: :dashboard do
    get "/", to: "dashboard#show", as: "dashboard"
    get "coming-soon", to: "dashboard#coming_soon"
  end

  # ref https://stackoverflow.com/questions/17743696/rails-routing-resources-with-only-custom-actions
  scope "/", controller: :pages do
    get :index
    get "about", to: "pages#about"
    get "privacy-policy", to: "pages#privacy_policy"
    get "code-of-conduct", to: "pages#code_of_conduct"
    get "anti-harassment", to: "pages#anti_harassment"
  end
end

app/models/physical_location.rb
# == Schema Information
#
# Table name: physical_locations
#
#  id                :uuid             not null, primary key
#  city              :text
#  country           :text
#  state_subdivision :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class PhysicalLocation < ApplicationRecord
  after_initialize :set_default_country

  with_options presence: true do
    validates :country
    validates :city
  end

  validates :state_subdivision,
            presence: { if: ->(location) { location.iso3166_subdivisions&.any? } },
            inclusion: {
              in: ->(location) { location.iso3166_subdivisions }, allow_blank: true,
              if: ->(location) { location.iso3166_country.present? }
            }

  before_save :capitalize_city!

  def self.default_country
    ISO3166::Country.find_country_by_alpha2("us").common_name
  end

  def iso3166_country
    ISO3166::Country.find_country_by_any_name(country)
  end

  def iso3166_subdivisions
    iso3166_country&.subdivision_names
  end

  private

  def capitalize_city!
    city.capitalize!
  end

  def set_default_country
    self.country ||= ISO3166::Country.find_country_by_alpha2("us").common_name
  end
end

app/controllers/physical_locations_controller.rb
class PhysicalLocationsController < ApplicationController
  include Pundit::Authorization

  before_action :authenticate_user!
  before_action :set_physical_location, only: %i[show edit update]

  after_action :verify_authorized

  # GET /physical_locations/1 or /physical_locations/1.json
  def show
  end

  # GET /physical_locations/new
  def new
    @physical_location = PhysicalLocation.new(physical_location_params)
    authorize @physical_location
  end

  # GET /physical_locations/1/edit
  def edit
  end

  # POST /physical_locations or /physical_locations.json
  def create
    @physical_location = PhysicalLocation.new(physical_location_params)
    authorize @physical_location

    respond_to do |format|
      if @physical_location.save
        format.html { redirect_to physical_location_url(@physical_location), notice: t(".create_success") }
        format.json { render :show, status: :created, location: @physical_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physical_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physical_locations/1 or /physical_locations/1.json
  def update
    respond_to do |format|
      if @physical_location.update(physical_location_params)
        format.html { redirect_to physical_location_url(@physical_location), notice: t(".update_success") }
        format.json { render :show, status: :ok, location: @physical_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physical_location.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_physical_location
    @physical_location = policy_scope(PhysicalLocation).find(params[:id])
    authorize @physical_location
  end

  # Only allow a list of trusted parameters through.
  def physical_location_params
    params.fetch(:physical_location, {}).permit(:city, :state_subdivision, :country)
  end
end

app/views/physical_locations/_form.html.erb
<%= form_with(model: physical_location, class: "contents") do |form| %>
  <% if physical_location.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(physical_location.errors.count, "error") %> prohibited this physical_location from being
        saved:</h2>

      <ul>
        <% physical_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render "physical_location_fields", form: form, physical_location: physical_location %>

  <div class="mt-4 inline-block">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/physical_locations/_physical_location.html.erb
<div id="<%= dom_id physical_location %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= physical_location.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State subdivision:</strong>
    <%= physical_location.state_subdivision %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Country:</strong>
    <%= physical_location.country %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this physical location", physical_location, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this physical location", edit_physical_location_path(physical_location), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/physical_locations/_physical_location_fields.erb
<% dynamic_select_path ||= new_physical_location_path %>
<div
  data-controller="dynamic-select search-params">
  <div class="w-full relative z-0 mt-4">
    <%= label_tag :country,
                  "Country",
                  class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
    <%= form.select(
          :country,
          options_for_select(ISO3166::Country.all_translated, selected: form.object.country),
          {},
          class: "appearance-none block mt-2 w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black",
          autocomplete: "off",
          data: { action: "change->search-params#encode change->dynamic-select#selectClick" }
        ) %>
    <a href="<%= dynamic_select_path %>"
       data-search-params-target="anchor"
       data-dynamic-select-target="selectClick"
       data-turbo-frame="<%= form.field_id(:state, :turbo_frame) %>"
       hidden></a>
  </div>
</div>

<%= turbo_frame_tag form.field_id(:state, :turbo_frame) do %>
  <% if form.object.iso3166_subdivisions.present? %>
    <div class="w-full relative z-0 mt-4">
      <%= form.select(
            :state_subdivision,
            form.object.iso3166_subdivisions,
            {},
            class: "appearance-none block mt-2 w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black",
            autocomplete: "off",
            data: { action: "change->dynamic-select#selectClick" }
          ) %>

      <%= label_tag :state_subdivision,
                    "State/Subdivision",
                    class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
    </div>
  <% end %>
<% end %>

<div class="w-full relative z-0 mt-4">
  <%= form.text_field :city,
                      placeholder: " ",
                      class: "appearance-none block w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black peer" %>
  <%= label_tag :city,
                "City",
                class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
</div>

app/views/physical_locations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing physical location</h1>

  <%= render "form", physical_location: @physical_location %>

  <%= link_to "Show this physical location", @physical_location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to physical locations", physical_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/physical_locations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Physical locations</h1>
    <%= link_to "New physical location", new_physical_location_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="physical_locations" class="min-w-full">
    <%= render @physical_locations %>
  </div>
</div>

app/views/physical_locations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New physical location</h1>

  <%= render "form", physical_location: @physical_location %>

  <%= link_to "Back to physical locations", physical_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/physical_locations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @physical_location %>

    <%= link_to "Edit this physical_location", edit_physical_location_path(@physical_location), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this physical_location", physical_location_path(@physical_location), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to physical_locations", physical_locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>