config/routes.rb
Rails.application.routes.draw do
  namespace :founder do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  namespace :investor do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  resources :physical_locations
  namespace :user_profile, path: :profile do
    resources :personals, path: :personal
    resources :professionals, path: :professional, except: [:new, :create]
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # TODO: omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
    require "sidekiq/web"
    Sidekiq::Web.app_url = "/"
    mount Sidekiq::Web => "/sidekiq"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#index", as: :app_index

  scope "dashboard", controller: :dashboard do
    get "/", to: "dashboard#show", as: "dashboard"
    get "coming-soon", to: "dashboard#coming_soon"
  end

  # ref https://stackoverflow.com/questions/17743696/rails-routing-resources-with-only-custom-actions
  scope "/", controller: :pages do
    get :index
    get "about", to: "pages#about"
    get "privacy-policy", to: "pages#privacy_policy"
    get "code-of-conduct", to: "pages#code_of_conduct"
    get "anti-harassment", to: "pages#anti_harassment"
  end
end

app/models/founder.rb
module Founder
  def self.table_name_prefix
    "founder_"
  end
end

app/models/founder/firm_role.rb
# == Schema Information
#
# Table name: founder_firm_roles
#
#  id                              :uuid             not null, primary key
#  departed_on                     :datetime
#  joined_at                       :datetime
#  ownership_confirmation_checkbox :boolean          default(FALSE), not null
#  ownership_percentage            :decimal(, )      not null
#  title                           :string           not null
#  visibility                      :integer          not null
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  founder_firm_id                 :uuid             not null
#  professional_profile_id         :uuid             not null
#
# Indexes
#
#  index_founder_firm_roles_on_founder_firm_id          (founder_firm_id)
#  index_founder_firm_roles_on_professional_profile_id  (professional_profile_id)
#
# Foreign Keys
#
#  fk_rails_...  (founder_firm_id => founder_firms.id)
#  fk_rails_...  (professional_profile_id => professionals_user_profiles.id)
#
class Founder::FirmRole < ApplicationRecord
  include ::VisibilityAdjustable

  has_paper_trail versions: { class_name: "Founder::FirmRoleVersion" }

  belongs_to :founder_firm,
             class_name: "Founder::Firm",
             inverse_of: :founder_firm_roles

  belongs_to :professional_profile,
             class_name: "UserProfile::Professional",
             inverse_of: :founder_firm_roles

  with_options presence: true do
    validates :title
    validates :ownership_percentage
  end

  validates :ownership_percentage, numericality: {
    less_than_or_equal_to: 100,
    greater_than_or_equal_to: 0
  }

  validates :ownership_confirmation_checkbox, inclusion: {
    in: [true],
    message: I18n.t("activerecord.models.founder.firm_role.must_confirm_ownership")
  }

  accepts_nested_attributes_for :founder_firm
end

app/models/founder/firm_role_version.rb
# == Schema Information
#
# Table name: founder_firm_role_versions
#
#  id         :bigint           not null, primary key
#  event      :string           not null
#  item_type  :string           not null
#  object     :json
#  whodunnit  :string
#  created_at :datetime
#  item_id    :uuid             not null
#
# Indexes
#
#  index_founder_firm_role_versions_on_item_type_and_item_id  (item_type,item_id)
#
class Founder::FirmRoleVersion < PaperTrail::Version
  self.table_name = :founder_firm_role_versions
end

app/models/founder/firm_version.rb
# == Schema Information
#
# Table name: founder_firm_versions
#
#  id         :bigint           not null, primary key
#  event      :string           not null
#  item_type  :string           not null
#  object     :json
#  whodunnit  :string
#  created_at :datetime
#  item_id    :uuid             not null
#
# Indexes
#
#  index_founder_firm_versions_on_item_type_and_item_id  (item_type,item_id)
#
class Founder::FirmVersion < PaperTrail::Version
  self.table_name = :founder_firm_versions
end

app/models/investor/firm_role.rb
# == Schema Information
#
# Table name: investor_firm_roles
#
#  id                           :uuid             not null, primary key
#  investment_target_customer   :text
#  investment_target_industries :text
#  investment_target_locations  :text
#  investment_target_stage      :text
#  title                        :text
#  why_here                     :text
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  investor_firm_id             :uuid             not null
#  physical_location_id         :uuid
#  professional_profile_id      :uuid             not null
#
# Indexes
#
#  index_investor_firm_roles_on_investor_firm_id         (investor_firm_id)
#  index_investor_firm_roles_on_physical_location_id     (physical_location_id)
#  index_investor_firm_roles_on_professional_profile_id  (professional_profile_id)
#
# Foreign Keys
#
#  fk_rails_...  (investor_firm_id => investor_firms.id)
#  fk_rails_...  (physical_location_id => physical_locations.id)
#  fk_rails_...  (professional_profile_id => professionals_user_profiles.id)
#
class Investor::FirmRole < ApplicationRecord
  has_paper_trail versions: { class_name: "Investor::FirmRoleVersion" }

  belongs_to :physical_location, dependent: :destroy

  belongs_to :investor_firm,
             class_name: "Investor::Firm",
             inverse_of: :investor_firm_roles

  belongs_to :professional_profile,
             class_name: "UserProfile::Professional",
             inverse_of: :investor_firm_roles

  with_options presence: true do
    validates :title
  end

  accepts_nested_attributes_for :investor_firm
  accepts_nested_attributes_for :physical_location
end

app/controllers/founder/firm_roles_controller.rb
class Founder::FirmRolesController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!

  before_action :set_founder_firms, only: %i[new create]
  before_action :set_founder_firm, only: %i[index edit update destroy]
  before_action :set_founder_firm_role, only: %i[show edit update destroy]

  after_action :verify_authorized

  # GET /founder/firm_roles or /founder/firm_roles.json
  def index
    @founder_firm_roles = Founder::FirmRole.all
  end

  # GET /founder/firm_roles/1 or /founder/firm_roles/1.json
  def show
  end

  # GET /founder/firm_roles/new
  def new
    @founder_firm_role = current_user
                         .professional_profile
                         .founder_firm_roles
                         .build(founder_firm_role_params)
    authorize @founder_firm_role
  end

  # GET /founder/firm_roles/1/edit
  def edit
  end

  # POST /founder/firm_roles or /founder/firm_roles.json
  def create
    @founder_firm_role = current_user
                         .professional_profile
                         .founder_firm_roles
                         .build(founder_firm_role_params)
    authorize @founder_firm_role

    respond_to do |format|
      if @founder_firm_role.save
        format.html { redirect_to founder_firm_role_url(@founder_firm_role), notice: t(".create_success") }
        format.json { render :show, status: :created, location: @founder_firm_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @founder_firm_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /founder/firm_roles/1 or /founder/firm_roles/1.json
  def update
    respond_to do |format|
      if @founder_firm_role.update(founder_firm_role_params)
        format.html { redirect_to founder_firm_role_url(@founder_firm_role), notice: t(".update_success") }
        format.json { render :show, status: :ok, location: @founder_firm_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @founder_firm_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /founder/firm_roles/1 or /founder/firm_roles/1.json
  def destroy
    @founder_firm_role.destroy

    respond_to do |format|
      format.html { redirect_to founder_firm_roles_url, notice: t(".destroy_success") }
      format.json { head :no_content }
    end
  end

  private

  def set_founder_firms
    @founder_firms = policy_scope(Founder::Firm).all.order(name: :asc)
    authorize @founder_firms
  end

  def set_founder_firm
    @founder_firm = policy_scope(Founder::Firm).friendly.find(params[:firm_id])
    authorize @founder_firm
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_founder_firm_role
    @founder_firm_role = Founder::FirmRole.find(params[:id])
    authorize @founder_firm_role
  end

  # Only allow a list of trusted parameters through.
  def founder_firm_role_params
    params.fetch(:founder_firm_role, {})
          .permit(:title,
                  :ownership_percentage,
                  :ownership_confirmation_checkbox,
                  :visibility,
                  :founder_firm_id,
                  :physical_location_id)
  end
end

app/controllers/founder/firms_controller.rb
class Founder::FirmsController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!

  before_action :set_founder_firm, only: %i[edit update destroy]

  after_action :verify_authorized

  # GET /founder/firms or /founder/firms.json
  def index
    @founder_firms = Founder::Firm.all
    authorize @founder_firms
  end

  # GET /founder/firms/1 or /founder/firms/1.json
  def show
    @founder_firm = Founder::Firm.friendly
                                 .includes(founder_firm_roles: { professional_profile: { user: :personal_profile } })
                                 .find(params[:id])
    @founder_firm_roles = @founder_firm.founder_firm_roles
    authorize @founder_firm
    authorize @founder_firm_roles
  end

  # GET /founder/firms/new
  def new
    @founder_firm = current_user
                    .professional_profile
                    .managed_founder_firms
                    .build(founder_firm_params)
    authorize @founder_firm
  end

  # GET /founder/firms/1/edit
  def edit
  end

  # POST /founder/firms or /founder/firms.json
  def create
    @founder_firm = current_user
                    .professional_profile
                    .managed_founder_firms
                    .build(founder_firm_params)
    @founder_firm.review_state_progression = true

    authorize @founder_firm

    respond_to do |format|
      if @founder_firm.save
        format.html do
          if params[:previous_referer]&.match?(new_founder_firm_role_url) || current_user.professional_profile.founder_firm_roles.empty?
            redirect_to new_founder_firm_role_url({
              founder_firm_role: { founder_firm_id: @founder_firm.id }
            }),
                        notice: t(".create_success_with_redirect")
          else
            redirect_to founder_firm_url(@founder_firm), notice: t(".create_success")
          end
        end
        format.json { render :show, status: :created, location: @founder_firm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @founder_firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /founder/firms/1 or /founder/firms/1.json
  def update
    respond_to do |format|
      if @founder_firm.update(founder_firm_params)
        format.html { redirect_to founder_firm_url(@founder_firm), notice: t(".update_success") }
        format.json { render :show, status: :ok, location: @founder_firm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @founder_firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /founder/firms/1 or /founder/firms/1.json
  def destroy
    @founder_firm.destroy

    respond_to do |format|
      format.html { redirect_to founder_firms_url, notice: t(".destroy_success") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_founder_firm
    @founder_firm = Founder::Firm.friendly.find(params[:id])
    authorize @founder_firm
  end

  # Only allow a list of trusted parameters through.
  def founder_firm_params
    params.fetch(:founder_firm, {})
          .permit(:id,
                  :name,
                  :field_visibility,
                  :ended_on,
                  :firm_kind,
                  :firm_kind_justification,
                  :founded_at,
                  :ended_on,
                  :short_description,
                  :long_description,
                  :site_url,
                  :target_customer,
                  :target_problem,
                  :visibility,
                  :headquarters_location_id,
                  :incorporation_location_id,
                  headquarters_location_attributes: [:city, :state_subdivision, :country])
  end
end

app/controllers/investor/firm_roles_controller.rb
class Investor::FirmRolesController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!

  before_action :set_investor_firm, only: %i[index edit update destroy]
  before_action :set_investor_firm_role, only: %i[edit update destroy]

  after_action :verify_authorized

  # GET /investor/firm_roles or /investor/firm_roles.json
  def index
    @investor_firm_roles = @investor_firm.investor_firm_roles.load
    authorize @investor_firm_roles
  end

  # GET /investor/firm_roles/new
  def new
    @investor_firms = Investor::Firm.all.order(name: :asc)
    @investor_firm_role = current_user
                          .professional_profile
                          .investor_firm_roles
                          .build(investor_firm_role_params)
    authorize @investor_firm_role
  end

  # GET /investor/firm_roles/1/edit
  def edit
  end

  # POST /investor/firm_roles or /investor/firm_roles.json
  def create
    @investor_firm_role = current_user
                          .professional_profile
                          .investor_firm_roles
                          .build(investor_firm_role_params)
    authorize @investor_firm_role

    respond_to do |format|
      if @investor_firm_role.save
        format.html { redirect_to investor_firm_url(@investor_firm_role.investor_firm_id), notice: t(".create_success") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investor/firm_roles/1 or /investor/firm_roles/1.json
  def update
    respond_to do |format|
      if @investor_firm_role.update(investor_firm_role_params)
        format.html { redirect_to investor_firm_firm_role_url(@investor_firm, @investor_firm_role), notice: t(".update_success") }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investor_firm_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investor/firm_roles/1 or /investor/firm_roles/1.json
  def destroy
    @investor_firm_role.destroy

    respond_to do |format|
      format.html { redirect_to investor_firm_roles_url, notice: t(".destroy.destroy_success") }
      format.json { head :no_content }
    end
  end

  private

  def set_investor_firm
    @investor_firm = Investor::Firm.friendly.find(params[:firm_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_investor_firm_role
    @investor_firm_role = Investor::FirmRole.find(params[:id])
    authorize @investor_firm_role
  end

  # Only allow a list of trusted parameters through.
  def investor_firm_role_params
    params.fetch(:investor_firm_role, {})
          .permit(:title,
                  :why_here,
                  :investment_target_stage,
                  :investment_target_customer,
                  :investment_target_industries,
                  :investor_firm_id,
                  :location_id,
                  :overview,
                  physical_location_attributes: [:city, :state_subdivision, :country])
  end
end

app/views/founder/firm_roles/_firm_role.html.erb
<div
  id="<%= dom_id firm_role %>"
  class="flex flex-col space-y-1 md:space-y-2">

  <div class="space-y-1 md:space-y-2 border-2 border-black outline-2 outline-white w-full p-4 rounded-lg">
    <%# Name %>
    <p class="">
      <strong class="font-bold">Name:</strong>
      <%# gross %>
      <%= firm_role.professional_profile.user.personal_profile.full_name %>
    </p>

    <%# Title %>
    <p class="">
      <strong class="font-bold">Title:</strong>
      <%= firm_role.title %>
    </p>
  </div>
</div>

app/views/founder/firm_roles/_form.html.erb
<%= form_with(model: founder_firm_role,
              class: "w-full") do |form| %>
  <div class="flex flex-row justify-end w-full">
    <div class="md:w-2/3">
      <%= render partial: "shared/error_messages",
                 locals: { resource: founder_firm_role,
                           error_message_header: t(".errors.messages.not_saved_header") } %>
    </div>
  </div>

  <div class="flex flex-col space-y-1 md:space-y-2 my-4">

    <%# Who're they with? What company? %>
    <div class="flex flex-col md:flex-row md:items-center">

      <h3 class="md:w-1/3 text-xl font-semibold text-gray-600 md:text-right md:text-center md:pr-8">
        Who <span class="block italic text-sm">Tell us which company you've founded</span>
      </h3>

      <div class="flex flex-col space-y-2 md:space-y-4 md:w-2/3 border-l-2 border-gray-300 outline-2 outline-white w-full my-4 pl-2 md:my-8 md:pl-8">
        <%# Founder firm %>
        <div class="flex flex-row w-full">
          <div class="flex flex-col md:flex-row w-full space-x-0 md:space-x-4 items-end">
            <div class="grow relative z-0 mt-4">
              <%= form.select(
                    :founder_firm_id,
                    options_from_collection_for_select(@founder_firms, "id", "name", form.object.founder_firm_id),
                    { include_blank: true },
                    class: "appearance-none block mt-2 w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black"
                  ) %>
              <%= label_tag :founder_firm_id,
                            "Company Name (required)",
                            class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            </div>
            <div>
              <%= link_to "Add a new Company",
                          new_founder_firm_path,
                          form_class: "inline",
                          class: "w-full rounded-lg py-2 px-5 bg-white text-black inline-block font-medium border-2 border-black cursor-pointer no-underline shadow-full-sm shadow-cyan-800/30 hover:shadow-cyan-700/60 duration-200" %>
            </div>
          </div>

        </div>
      </div>
    </div>

    <%# About the person/role %>
    <div class="flex flex-col md:flex-row md:items-center">

      <h3 class="md:w-1/3 text-xl font-semibold text-gray-600 md:text-right md:text-center md:pr-8">
        About <span class="block italic text-sm">Tell us about your role</span>
      </h3>

      <div class="flex flex-col space-y-2 md:space-y-4 md:w-2/3 border-l-2 border-gray-300 outline-2 outline-white w-full my-4 pl-2 md:my-8 md:pl-8">
        <%# Title %>
        <div class="flex flex-col">
          <div class="flex flex-col md:flex-row space-x-0 md:space-x-4 ">

            <div class="w-full relative z-0 mt-4">
              <%= form.text_field :title,
                                  placeholder: " ",
                                  class: "appearance-none block w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black peer" %>
              <%= label_tag :title,
                            "Title/Role (required)",
                            class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            </div>
          </div>
        </div>

        <%# Ownership %>
        <div class="flex flex-col">
          <%# Ownership percentage %>
          <div class="flex flex-col md:flex-row space-x-0 md:space-x-4 ">
            <div class="w-full relative z-0 mt-4">

              <div class="flex flex-row">
                <span class="flex rounded rounded-r-none items-center bg-gray-200 px-3 font-bold text-gray-800">%</span>
                <%= form.number_field :ownership_percentage,
                                      placeholder: " ",
                                      step: 0.5,
                                      class: "rounded-l-none appearance-none block w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black peer" %>
              </div>
              <%= label_tag :ownership_percentage,
                            "Ownership Percentage (required)",
                            class: "absolute uppercase tracking-wide text-black text-xs font-bold duration-200 transform -translate-y-6 scale-75 top-2 -z-10 peer-placeholder-shown:px-2 origin-[0] peer-focus:left-0 peer-focus:px-0 peer-focus:text-gray-700 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            </div>
          </div>

          <%# Ownership confirmation checkbox %>
          <div class="flex mt-4">
            <div class="flex items-center h-5">
              <%= form.check_box :ownership_confirmation_checkbox,
                                 "aria-describedby" => "ownership-confirmation-text",
                                 :class => "w-4 h-4 text-cyan-800/60 bg-gray-100 border-gray-600 focus:ring-cyan-800/60 focus:ring-2 rounded" %>
            </div>
            <div class="ml-2 text-sm">
              <%= label_tag :ownership_confirmation_checkbox,
                            t(".ownership_confirmation_label") + "(REQUIRED)",
                            class: "font-medium text-gray-600" %>
              <p id="ownership-confirmation-text" class="text-xs font-normal text-gray-500 dark:text-gray-300">
                <%= t(".ownership_confirmation_sublabel") %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%# Profile Visibility %>
    <div class="flex flex-col md:flex-row md:items-center">

      <h3 class="md:w-1/3 text-xl font-semibold text-gray-600 md:text-right md:text-center md:pr-8">
        Visibility
      </h3>

      <div class="flex flex-col space-y-2 md:space-y-4 md:w-2/3 border-l-2 border-gray-300 outline-2 outline-white w-full my-4 pl-2 md:my-8 md:pl-8">

        <div class="flex flex-col mt-4">
          <p class="text-xs text-gray-600">
            Select the visibility level of this role. <span class="uppercase font-semibold">(required)</span>
          </p>

          <%= form.select(
                :visibility,
                Founder::FirmRole.visibilities.key(0),
                {},
                class: "appearance-none block mt-2 w-full bg-cyan-800/60 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 leading-tight focus:outline-none focus:border-cyan-800/60 focus:bg-white focus:text-black"
              ) do %>
            <% Founder::FirmRole.visibilities.each_pair do |k, v| %>
              <%= tag.option(k, value: k, html: { class: "" }) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="flex justify-center items-center text-center w-full md:justify-end mt-4">
      <%= form.submit t(".submit"),
                      class: "w-full md:w-1/5 rounded-lg py-2 px-5 bg-white text-black inline-block font-medium border-2 border-black cursor-pointer no-underline shadow-full-sm shadow-cyan-800/30 hover:shadow-cyan-700/60 duration-200" %>
    </div>

  </div>
<% end %>

app/views/founder/firm_roles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing firm role</h1>

  <%= render "form", founder_firm_role: @founder_firm_role %>

  <%= link_to "Show this firm role", @founder_firm_role, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to firm roles", founder_firm_roles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/founder/firm_roles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Firm roles</h1>
    <%= link_to "New firm role", new_founder_firm_role_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="founder_firm_roles" class="min-w-full">
    <%= render @founder_firm_roles %>
  </div>
</div>

app/views/founder/firm_roles/new.html.erb
<div class="flex flex-col md:space-y-4 md:space-x-0 w-full md:mx-0 mx-auto">
  <h2 class="text-3xl font-semibold mx-auto">
    Tell us about your role!
  </h2>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render "form", founder_firm_role: @founder_firm_role %>
</div>

app/views/founder/firm_roles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @founder_firm_role %>

    <%= link_to "Edit this founder_firm_role", edit_founder_firm_role_path(@founder_firm_role), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this founder_firm_role", founder_firm_role_path(@founder_firm_role), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to founder_firm_roles", founder_firm_roles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>