config/routes.rb
Rails.application.routes.draw do
  namespace :founder do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  namespace :investor do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  resources :physical_locations
  namespace :user_profile, path: :profile do
    resources :personals, path: :personal
    resources :professionals, path: :professional, except: [:new, :create]
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # TODO: omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
    require "sidekiq/web"
    Sidekiq::Web.app_url = "/"
    mount Sidekiq::Web => "/sidekiq"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#index", as: :app_index

  scope "dashboard", controller: :dashboard do
    get "/", to: "dashboard#show", as: "dashboard"
    get "coming-soon", to: "dashboard#coming_soon"
  end

  # ref https://stackoverflow.com/questions/17743696/rails-routing-resources-with-only-custom-actions
  scope "/", controller: :pages do
    get :index
    get "about", to: "pages#about"
    get "privacy-policy", to: "pages#privacy_policy"
    get "code-of-conduct", to: "pages#code_of_conduct"
    get "anti-harassment", to: "pages#anti_harassment"
  end
end

app/models/user_profile.rb
module UserProfile
  ALL_PROFILE_KINDS = %w[professional personal]
  def self.table_name_suffix
    "_user_profiles"
  end
end

app/models/user_profile/personal.rb
# == Schema Information
#
# Table name: personals_user_profiles
#
#  id                     :uuid             not null, primary key
#  email_address          :string(319)      not null
#  first_name             :text
#  freeform_pronouns      :text
#  headline               :string(128)
#  last_name              :text
#  linkedin_url           :text
#  original_email_address :string           not null
#  original_linkedin_url  :text
#  overview               :string(1024)
#  prepopulated_pronouns  :text             not null
#  pronoun_visibility     :boolean
#  visibility             :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :uuid             not null
#
# Indexes
#
#  index_personals_user_profiles_on_email_address       (email_address) UNIQUE
#  index_personals_user_profiles_on_pronoun_visibility  (pronoun_visibility)
#  index_personals_user_profiles_on_user_id             (user_id) UNIQUE
#  index_personals_user_profiles_on_visibility          (visibility)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class UserProfile::Personal < ApplicationRecord
  has_paper_trail versions: { class_name: "UserProfile::PersonalVersion" }

  belongs_to :user

  #  - ref:
  #   https://www.gsrc.princeton.edu/creating-inclusive-forms
  #   https://www.keshetonline.org/resources/forms/
  #   https://uwm.edu/lgbtrc/support/gender-pronouns/
  attribute :prepopulated_pronouns, :integer

  enum prepopulated_pronouns: {
    "She/Her/Hers" => 0,
    "He/Him/His" => 1,
    "Ze/Hir/Hirs" => 2,
    "They/Them/Theirs" => 3,
    "It/It/Its" => 4,
    "Just my name, please! (no pronoun)" => 5,
    "Not listed" => 6
  }

  enum visibility: {
    "Public" => 0,
    "Internal (members-only)" => 1,
    "Private (admins-only)" => 2
  }

  with_options presence: true do
    validates :first_name
    validates :last_name
    validates :linkedin_url
    validates :prepopulated_pronouns
    validates :visibility
  end

  validates :pronoun_visibility, inclusion: { in: [true, false] }

  validates :email_address,
            length: { in: 4..319 },
            uniqueness: true,
            unless: ->(profile) { profile.email_address.blank? }

  validates :linkedin_url,
            length: { in: 17..1024 },
            uniqueness: true,
            unless: ->(profile) { profile.linkedin_url.blank? }

  validates :linkedin_url,
            url: { public_suffix: true },
            unless: ->(profile) { profile.linkedin_url.blank? }

  validates :headline, length: { maximum: 128 }
  validates :overview, length: { maximum: 1024 }

  validates :freeform_pronouns, length: { maximum: 32 }
  validates :prepopulated_pronouns,
            inclusion: prepopulated_pronouns.keys,
            unless: ->(profile) { profile.prepopulated_pronouns.blank? }

  encrypts :first_name, deterministic: false
  encrypts :last_name, deterministic: false
  encrypts :overview, deterministic: false
  encrypts :freeform_pronouns, deterministic: false
  encrypts :prepopulated_pronouns, deterministic: false

  encrypts :email_address, deterministic: true, ignore_case: true
  encrypts :linkedin_url, deterministic: true, ignore_case: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user_profile/personal_version.rb
# == Schema Information
#
# Table name: user_profile_personal_versions
#
#  id         :bigint           not null, primary key
#  event      :string           not null
#  item_type  :string           not null
#  object     :json
#  whodunnit  :string
#  created_at :datetime
#  item_id    :uuid             not null
#
# Indexes
#
#  index_user_profile_personal_versions_on_item_type_and_item_id  (item_type,item_id)
#
class UserProfile::PersonalVersion < PaperTrail::Version
  self.table_name = :user_profile_personal_versions
end

app/models/user_profile/professional.rb
# == Schema Information
#
# Table name: professionals_user_profiles
#
#  id         :uuid             not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid             not null
#
# Indexes
#
#  index_professionals_user_profiles_on_user_id  (user_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class UserProfile::Professional < ApplicationRecord
  has_paper_trail versions: { class_name: "UserProfile::ProfessionalVersion" }

  belongs_to :user

  has_many :investor_firm_roles,
           class_name: "Investor::FirmRole",
           inverse_of: :professional_profile,
           foreign_key: :professional_profile_id,
           dependent: :destroy

  has_many :founder_firm_roles,
           class_name: "Founder::FirmRole",
           inverse_of: :professional_profile,
           foreign_key: :professional_profile_id,
           dependent: :destroy

  has_many :managed_founder_firms,
           class_name: "Founder::Firm",
           inverse_of: :professional_profile,
           foreign_key: :professional_profile_id,
           dependent: :destroy

  has_many :managed_investor_firms,
           class_name: "Investor::Firm",
           inverse_of: :professional_profile,
           foreign_key: :professional_profile_id,
           dependent: :destroy

  def any_founder_profiles?
    managed_founder_firms.any? || founder_firm_roles.any?
  end

  def any_investor_profiles?
    managed_investor_firms.any? || investor_firm_roles.any?
  end

  def any_profiles?
    any_founder_profiles? || any_investor_profiles? # check if any founder, investor, vendor profiles exist
  end

  def has_no_profiles?
    !any_profiles?
  end
end

app/models/user_profile/professional_version.rb
# == Schema Information
#
# Table name: user_profile_professional_versions
#
#  id         :bigint           not null, primary key
#  event      :string           not null
#  item_type  :string           not null
#  object     :json
#  whodunnit  :string
#  created_at :datetime
#  item_id    :uuid             not null
#
# Indexes
#
#  index_up_professional_versions_on_item_type_and_item_id  (item_type,item_id)
#
class UserProfile::ProfessionalVersion < PaperTrail::Version
  self.table_name = :user_profile_professional_versions
end

app/controllers/user_profile/personals_controller.rb
class UserProfile::PersonalsController < ApplicationController
  include Pundit::Authorization

  layout "dashboard", except: [:new]

  before_action :authenticate_user!
  before_action :disallow_overwrite_current_profile, only: [:new, :create]
  before_action :set_user_profile_personal, only: %i[show edit update]

  after_action :verify_authorized

  # GET /user_profile/personals/1 or /user_profile/personals/1.json
  def show
  end

  def new
    @user_profile_personal = current_user.build_personal_profile
    authorize @user_profile_personal
  end

  # GET /user_profile/personals/1/edit
  def edit
  end

  def create
    @user_profile_personal = current_user
                             .build_personal_profile(user_profile_personal_params)
    authorize @user_profile_personal

    respond_to do |format|
      if @user_profile_personal.save
        format.html { redirect_to dashboard_path, notice: t(".create_success") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profile/personals/1 or /user_profile/personals/1.json
  def update
    respond_to do |format|
      if @user_profile_personal.update(user_profile_personal_params)
        format.html { redirect_to user_profile_personal_url(@user_profile_personal), notice: t(".update_success") }
        format.json { render :show, status: :ok, location: @user_profile_personal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile_personal.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def disallow_overwrite_current_profile
    if current_user.personal_profile.present?
      redirect_back_or_to dashboard_url, allow_other_host: false
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user_profile_personal
    @user_profile_personal = UserProfile::Personal.find(params[:id])
    authorize @user_profile_personal
  end

  # Only allow a list of trusted parameters through.
  def user_profile_personal_params
    params.require(:user_profile_personal)
          .permit(
            :email_address,
            :first_name,
            :freeform_pronouns,
            :headline,
            :last_name,
            :linkedin_url,
            :overview,
            :prepopulated_pronouns,
            :pronoun_visibility,
            :visibility
          )
  end
end

app/controllers/user_profile/professionals_controller.rb
class UserProfile::ProfessionalsController < ApplicationController
  include ProfessionalProfileable
  include Pundit::Authorization

  before_action :authenticate_user!
  before_action :set_user_profile_professional, only: [:show, :edit, :update]

  after_action :verify_authorized

  rescue_from Pundit::NotAuthorizedError, with: :unauthorized_access

  def index
    @user_profile_professionals = policy_scope(UserProfile::Professional).all
    authorize @user_profile_professionals
  end

  # GET /user_profile/professionals/1 or /user_profile/professionals/1.json
  def show
    @available_profile_kinds = creatable_profile_kinds
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user_profile_professional.update(user_profile_professional_params)
        format.html { redirect_to user_profile_professional_url(@user_profile_professional), notice: t(".update_success") }
        format.json { render :show, status: :ok, location: @user_profile_professional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile_professional.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_profile_professional
    @user_profile_professional = policy_scope(UserProfile::Professional).find(params[:id])
    authorize @user_profile_professional
  end

  # Only allow a list of trusted parameters through.
  def user_profile_professional_params
    params.fetch(:user_profile_professional, {})
  end
end

app/views/user_profile/professionals/_form.html.erb
<%= form_with(model: user_profile_professional, class: "contents") do |form| %>
  <% if user_profile_professional.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user_profile_professional.errors.count, "error") %> prohibited this user_profile_professional from being saved:</h2>

      <ul>
        <% user_profile_professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_profile/professionals/_professional.html.erb
<% if @user_profile_professional.has_no_profiles? %>
  <div class="flex flex-col">
    <div class="flex flex-col items-center">

      <h1 class="font-sans text-3xl md:text-5xl font-bold uppercase leading-tight text-center mt-2 md:mt-4">
        <%= t(".header") %>
      </h1>

      <h2 class="text-gray-700 md:text-3xl mt-2 md:mt-8">
        I am a[n]...
      </h2>
    </div>

    <%= content_tag :div, class: "w-full mt-2 md:mt-8" do %>
      <section id="new-profile">
        <div class="flex flex-col md:flex-row md:grow md:justify-around space-y-2 md:space-y-0 md:space-x-4">
          <%# Placeholders %>

          <%= link_to new_investor_firm_role_path, class: "no-underline" do %>
            <div class="border-4 md:border-8 border-gray-800 text-left p-6 md:p-8  shadow-full-md shadow-cyan-900/30 hover:shadow-cyan-700/60 duration-200">
              <h3 class="font-sans text-xl md:text-5xl font-bold uppercase my-2 md:my-4 leading-tight">
                Investor
              </h3>
            </div>
          <% end %>

          <%= link_to new_founder_firm_role_path, class: "no-underline" do %>
            <div class="border-4 md:border-8 border-gray-800 text-left p-6 md:p-8  shadow-full-md shadow-cyan-900/50 hover:shadow-cyan-700/60 duration-200">
              <h3 class="font-sans text-xl md:text-5xl font-bold uppercase my-2 md:my-4 leading-tight">
                Founder
              </h3>
            </div>
          <% end %>

          <%#
            <%= link_to new_investor_firm_role_path, class: "no-underline" do %#>
              <div class="border-4 md:border-8 border-gray-800 text-left p-6 md:p-8  shadow-full-md shadow-cyan-900/30 hover:shadow-cyan-700/60 duration-200">
                <h3 class="font-sans text-xl md:text-5xl font-bold uppercase my-2 md:my-4 leading-tight">
                  Vendor
                </h3>
              </div>
            <% end %#>
          %>

        </div>
      </section>
    <% end %>

    <div class="flex flex-col items-center mt-1 md:mt-4">
      <p class="text-center text-gray-700 text-sm md:text-base">
        Are you multi-faceted? Don't worry! You can create more profiles later!
      </p>
    </div>
  </div>
<% else %>
<% end %>

app/views/user_profile/professionals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing professional</h1>

  <%= render "form", user_profile_professional: @user_profile_professional %>

  <%= link_to "Show this professional", @user_profile_professional, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to professionals", user_profile_professionals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_profile/professionals/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Professionals</h1>
    <%= link_to "New professional", new_user_profile_professional_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="user_profile_professionals" class="min-w-full">
    <%= render @user_profile_professionals %>
  </div>
</div>

app/views/user_profile/professionals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New professional</h1>

  <%= render "form", user_profile_professional: @user_profile_professional %>

  <%= link_to "Back to professionals", user_profile_professionals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_profile/professionals/show.html.erb
<div class="mx-auto w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render @user_profile_professional %>
</div>