config/routes.rb
Rails.application.routes.draw do
  namespace :founder do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  namespace :investor do
    resources :firm_roles
    resources :firms do
      resources :firm_roles
    end
  end

  resources :physical_locations
  namespace :user_profile, path: :profile do
    resources :personals, path: :personal
    resources :professionals, path: :professional, except: [:new, :create]
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # TODO: omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
    require "sidekiq/web"
    Sidekiq::Web.app_url = "/"
    mount Sidekiq::Web => "/sidekiq"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#index", as: :app_index

  scope "dashboard", controller: :dashboard do
    get "/", to: "dashboard#show", as: "dashboard"
    get "coming-soon", to: "dashboard#coming_soon"
  end

  # ref https://stackoverflow.com/questions/17743696/rails-routing-resources-with-only-custom-actions
  scope "/", controller: :pages do
    get :index
    get "about", to: "pages#about"
    get "privacy-policy", to: "pages#privacy_policy"
    get "code-of-conduct", to: "pages#code_of_conduct"
    get "anti-harassment", to: "pages#anti_harassment"
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 mt-12">
  <div class="container max-w-6xl py-6 mx-auto md:px-10">
    <div class="w-full flex flex-col md:flex-row items-center justify-center space-y-4 md:space-y-0 md:space-x-4">
      <%# Logo %>
      <%= link_to app_index_url do %>
        <%= image_tag "logo_dark_bg_750px.png", class: "flex-1 mx-auto rounded-full max-h-14 shadow-full-lg shadow-cyan-800/50 hover:shadow-cyan-700/50 duration-200" %>
      <% end %>

      <%# Menus %>
      <div class="w-full md:w-auto flex flex-1 flex-col md:flex-row md:justify-between items-center space-y-4 md:space-y-0 md:space-x-6 md:ml-3 text-white text-center">
        <div class="w-1/3 md:w-auto flex flex-col pb-2 md:pb-0 items-center justify-center md:justify-start space-y-4 text-white md:flex-row md:space-y-0 border-b-2 border-b-gray-500 md:border-b-0">
          <div class="flex flex-col justify-center group h-10">
            <% if current_user %>
              <%= button_to "Sign out", destroy_user_session_path, method: :delete,
                                                                   class: "no-underline",
                                                                   form: {
                                                                     # https://github.com/rails/rails/issues/44170#issuecomment-1069644509
                                                                     data: { turbo_method: :delete }
                                                                   } %>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "no-underline" %>
            <% end %>
            <div class="mx-1 border-b border-2 border-transparent group-hover:border-cyan-800/50"></div>
          </div>
        </div>

        <div class="w-1/3 md:w-auto flex flex-col md:flex-row space-y-4 md:space-y-0">
          <!-- https://github.com/tailwindlabs/tailwindcss/discussions/2466 -->
          <div class="flex flex-col justify-center group h-10">
            <%= link_to "Code of Conduct", code_of_conduct_url, class: "no-underline pr-2 md:border-r md:border-white" %>
            <div class="mr-2 border-b border-2 border-transparent group-hover:border-cyan-800/50"></div>
          </div>

          <div class="flex flex-col justify-center group h-10">
            <%= link_to "Anti-Harassment Policy", anti_harassment_url, class: "no-underline px-2 md:border-r md:border-white" %>
            <div class="mx-2 border-b border-2 border-transparent group-hover:border-cyan-800/50"></div>
          </div>

          <div class="flex flex-col justify-center group h-10">
            <%= link_to "Privacy Policy", privacy_policy_url, class: "no-underline pl-2" %>
            <div class="ml-2 border-b border-2 border-transparent group-hover:border-cyan-800/50"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div
  class="container max-w-6xl mx-auto md:px-6 md:py-4 my-4">
  <div
    class="flex justify-between items-center md:flex-row mx-4 md:mx-0">

    <div class="flex flex-row md:mx-auto my-2 items-center z-[100]">
      <%= link_to app_index_url do %>
        <%= image_tag "logo_dark_bg_750px.png", class: "flex-1 mx-auto rounded-full max-h-14 shadow-full-lg shadow-cyan-800/50 hover:shadow-cyan-700/50 duration-200" %>
      <% end %>

      <p class="hidden md:block pl-4 text-3xl md:text-5xl font-sans align-middle font-semibold">
        <span class="text-gray-400">[Re]</span>Launch
      </p>
    </div>

    <%# Via the Tailwind from Scratch course on O'Reilly %>
    <div class="md:hidden">
      <button
        data-menu-nav-target="button"
        data-action="click->menu-nav#toggle"
        type="button"
        class="z-[100] block hamburger md:hidden focus:outline-none">
        <span class="hamburger-top"></span>
        <span class="hamburger-middle"></span>
        <span class="hamburger-bottom"></span>
      </button>
    </div>

  </div>

  <%# TODO: This should be a hamburger menu %>
  <% if current_layout == "application" %>
    <%= content_tag :div, class: "hidden md:flex items-center md:justify-end", data: { "menu-nav-target": "menu" } do %>
      <%= render "layouts/nav" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<div
  class="absolute md:static top-0 bottom-0 left-0 w-full md:w-auto flex flex-col min-h-screen md:min-h-0 py-1 md:py-0 pl-12 md:pl-0 text-lg md:text-base text-white md:text-black z-[80] bg-cyan-800 md:bg-inherit md:min-h-0 md:items-center md:flex-rowmd:justify-end">

  <div class="flex flex-col md:flex-row pt-36 md:pt-0 md:space-x-8">

    <% if current_user %>
      <div class="group md:block">
        <%= link_to "Dashboard", dashboard_url, class: "no-underline md:border-r md:border-white hover:underline" %>
        <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 md:border-blue-400 md:group-hover:opacity-100"></div>
      </div>

      <div class="group md:block">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete,
                                                             class: "no-underline hover:underline",
                                                             form: {
                                                               # https://github.com/rails/rails/issues/44170#issuecomment-1069644509
                                                               data: { turbo_method: :delete }
                                                             } %>
        <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 md:border-blue-400 md:group-hover:opacity-100"></div>
      </div>
    <% else %>

      <%# Static %>
      <div class="group md:block">
        <%= link_to "About", about_url, class: "no-underline md:border-r md:border-white hover:underline" %>
        <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 md:border-blue-400 md:group-hover:opacity-100"></div>
      </div>

      <div class="group md:block">
        <%= link_to "Log in", new_user_session_path, class: "no-underline hover:underline" %>
        <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 md:border-blue-400 md:group-hover:opacity-100"></div>
      </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : t(".title") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <script src="https://kit.fontawesome.com/b1ed12b0ad.js" crossorigin="anonymous"></script>
    <%= render "shared/analytics_resources" %>
  </head>

  <body class="bg-white">
    <div class="flex flex-col min-h-screen">

      <div
        class="flex flex-col"
        data-controller="menu-nav">
        <%= render "layouts/header" %>
      </div>

      <main class="container max-w-6xl mx-auto px-3 grow">
        <%= yield %>
      </main>

      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:page_title) ? yield(:page_title) : t(".title") %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <%= javascript_importmap_tags %>
  <%= hotwire_livereload_tags if Rails.env.development? %>
  <script src="https://kit.fontawesome.com/b1ed12b0ad.js" crossorigin="anonymous"></script>
  <%= render "shared/analytics_resources" %>
</head>

<body class="bg-white">
<div
  class="flex flex-col min-h-screen"
  data-controller="menu-nav">
  <%= render "layouts/header" %>

  <div class="container max-w-6xl mx-auto px-3 grow">
    <div class="flex">

      <div>

        <nav
          data-menu-nav-target="menu"
          class="hidden absolute top-0 bottom-0 left-0 z-[80] w-full flex-col min-h-screen py-1 pl-12 text-lg text-white bg-cyan-800 md:bg-inherit md:static md:flex md:w-48 md:min-h-0 md:p-6 md:text-base md:text-gray-600 md:bg-inherit md:min-h-0 md:items-center md:justify-start md:border-r-2 md:border-gray-100">

          <div class="flex flex-col md:flex-row pt-28 md:pt-0 md:space-x-8">
            <ul class="leading-8 space-y-4">

              <li><span class="text-2xl"><a class="no-underline" href="/dashboard">Dashboard</a></span></li>
              <li>
                <span class="text-2xl">Profiles</span>
                <ul class="list-none ml-5">
                  <li>
                    <%= link_to "Personal",
                                edit_user_profile_personal_path(current_user.personal_profile),
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                  <li>
                    <%= link_to "Founder",
                                coming_soon_path,
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                  <li>
                    <%= link_to "Investor",
                                coming_soon_path,
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                </ul>
              </li>
              <li>
                <span class="text-2xl">Resources</span>
                <ul class="list-none ml-5">
                  <li>
                    <%= link_to "Events",
                                coming_soon_path,
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                  <li>
                    <%= link_to "Stand-up",
                                coming_soon_path,
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                  <li>
                    <%= link_to "Learn",
                                coming_soon_path,
                                class: "font-normal no-underline hover:underline" %>
                  </li>
                </ul>
              </li>
              <li>
                <div class="group md:block">
                  <%= button_to "Sign out", destroy_user_session_path, method: :delete,
                                                                       class: "no-underline hover:underline text-2xl",
                                                                       form: {
                                                                         # https://github.com/rails/rails/issues/44170#issuecomment-1069644509
                                                                         data: { turbo_method: :delete }
                                                                       } %>
                  <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 md:border-blue-400 md:group-hover:opacity-100"></div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </div>

      <main class="grow">
        <%= yield %>
      </main>
    </div>
  </div>

  <%= render "layouts/footer" %>
</div>

</body>
</html>